default_platform(:android)

platform :android do

  desc "build, test and deploy application to Google Play"
  lane :build_test_deploy do
    spotless_check()
    test()
    deploy()
  end

  lane :build_test do
    spotless_check()
    test()
    build()
  end

  #PRIVATE
  desc "Build"
  private_lane :build do
    gradle(task: "bundleRelease")
  end

  #PRIVATE
  desc "Test"
  private_lane :test do
    gradle(task: "testDebugUnitTest")
  end


  #PRIVATE
  desc "Spotless check"
  private_lane :spotless_check do
    gradle(task: "spotlessCheck")
  end


  desc "Deploy a new version to Google Play internal"
  private_lane :deploy do

    gradle(task: "bundleRelease")
    @release_bundle = "app/build/outputs/bundle/release/app-release.aab"

    upload_to_play_store(
      track: "internal",
      aab: @release_bundle,
      json_key: "google_play_service_account.json",
      validate_only: false,
      skip_upload_apk: true,
    )
  end

end
